import type { Song } from "./interface/Song";
import type { Singer } from "./interface/Singer";
import type { Setlist } from "./interface/Setlist";

export const NOTES = [
  "C",
  "C#",
  "D",
  "D#",
  "E",
  "F",
  "F#",
  "G",
  "G#",
  "A",
  "Bb",
  "B",
];

export const SONGS: Song[] = [
  {
    id: 1,
    title: "Celebrate Jesus / Jesus is Alive",
    artist: "Don Moen / Ron Kenoly",
    key: "C",
    content: `[INTRO]\n | C | F - G |\n| C | F - G |\n| C | F - G |\n| C | Ab - Bb |\n\n[VERSE]\nC   F    G          C   F - G\nCelebrate Jesus celebrate\nC   F    G          C   Ab - Bb\nCelebrate Jesus celebrate\nC   F    G          C   F - G\nCelebrate Jesus celebrate\nC   F    G          C \nCelebrate Jesus celebrate\n\n[CHORUS]\nG            Am\nHe is risen. He is risen\nG            Am\nAnd He lives forevermore\nG           Am\nHe is risen He is risen\nG    F\nCome on and celebrate\nG              C\nThe resurrection of our Lord`,
  },
  {
    id: 2,
    title: "Worthy is the Lamb",
    artist: "Hillsong Worship",
    key: "G",
    content: `[Intro]\nEm G Em\n\n[Verse 1]\nG                 C           G\nThank you for the cross Lord\n                  C     D   G\nThank you for the price You paid\n               D       Em\nBearing all my sin and shame\n   D        C\nIn love You came\n    Am7  G       D\nAnd gave amazing grace`,
  },
  {
    id: 3,
    title: "Way Maker",
    artist: "Sinach / Leeland",
    key: "G",
    content: "[VERSE 1]\nYou are here moving in our midst...",
  },
  {
    id: 4,
    title: "Goodness of God",
    artist: "Bethel Music",
    key: "Ab",
    content: "[VERSE 1]\nI love You Lord...",
  },
  {
    id: 5,
    title: "At the Cross",
    artist: "Holan Davis",
    key: "E",
    content: `[Verse 1]\n         E    A       B \nAt the Cross, I find peace`,
  },
  {
    id: 6,
    title: "Amazing Grace (My Chains Are Gone)",
    artist: "Chris Tomlin",
    key: "G",
    content: "[VERSE 1]\nAmazing grace how sweet the sound...",
  },
  {
    id: 7,
    title: "How Great Is Our God",
    artist: "Chris Tomlin",
    key: "C",
    content: "[VERSE 1]\nThe splendor of a King...",
  },
  {
    id: 8,
    title: "10,000 Reasons",
    artist: "Matt Redman",
    key: "G",
    content: "[CHORUS]\nBless the Lord O my soul...",
  },
  {
    id: 9,
    title: "What A Beautiful Name",
    artist: "Hillsong Worship",
    key: "D",
    content: "[VERSE 1]\nYou were at the creation...",
  },
  {
    id: 10,
    title: "Lion and the Lamb",
    artist: "Bethel Music",
    key: "B",
    content: "[VERSE 1]\nHe's coming on the clouds...",
  },
  {
    id: 11,
    title: "O Come to the Altar",
    artist: "Elevation Worship",
    key: "B",
    content: "[VERSE 1]\nAre you hurting and broken within...",
  },
  {
    id: 12,
    title: "Living Hope",
    artist: "Phil Wickham",
    key: "D",
    content: "[VERSE 1]\nHow great the chasm that lay between us...",
  },
  {
    id: 13,
    title: "Build My Life",
    artist: "Housefires",
    key: "G",
    content: "[VERSE 1]\nWorthy of every song we could ever sing...",
  },
  {
    id: 14,
    title: "Who You Say I Am",
    artist: "Hillsong Worship",
    key: "G",
    content: "[VERSE 1]\nWho am I that the highest King...",
  },
  {
    id: 15,
    title: "King of Kings",
    artist: "Hillsong Worship",
    key: "D",
    content: "[VERSE 1]\nIn the darkness we were waiting...",
  },
  {
    id: 16,
    title: "Graves Into Gardens",
    artist: "Elevation Worship",
    key: "B",
    content: "[VERSE 1]\nI searched the world...",
  },
  {
    id: 17,
    title: "The Blessing",
    artist: "Kari Jobe / Cody Carnes",
    key: "B",
    content: "[VERSE 1]\nThe Lord bless you and keep you...",
  },
  {
    id: 18,
    title: "Holy Spirit",
    artist: "Francesca Battistelli",
    key: "D",
    content: "[VERSE 1]\nThere's nothing worth more...",
  },
  {
    id: 19,
    title: "Cornerstone",
    artist: "Hillsong Worship",
    key: "C",
    content: "[VERSE 1]\nMy hope is built on nothing less...",
  },
  {
    id: 20,
    title: "Hosanna",
    artist: "Hillsong UNITED",
    key: "E",
    content: "[VERSE 1]\nI see the King of glory...",
  },
  {
    id: 21,
    title: "Tremble",
    artist: "Mosaic MSC",
    key: "A",
    content: "[VERSE 1]\nPeace bring it all to peace...",
  },
  {
    id: 22,
    title: "Reckless Love",
    artist: "Cory Asbury",
    key: "Gb",
    content: "[VERSE 1]\nBefore I spoke a word...",
  },
];

export const SINGERS: Singer[] = [
  {
    id: 1,
    name: "John Doe",
    role: "Worship Leader",
    img: "https://i.pravatar.cc/150?u=1",
  },
  {
    id: 2,
    name: "Jane Smith",
    role: "Vocalist",
    img: "https://i.pravatar.cc/150?u=2",
  },
  {
    id: 3,
    name: "David Evans",
    role: "Worship Leader",
    img: "https://i.pravatar.cc/150?u=3",
  },
  {
    id: 4,
    name: "Sarah Jenkins",
    role: "Vocalist",
    img: "https://i.pravatar.cc/150?u=4",
  },
  {
    id: 5,
    name: "Michael Brown",
    role: "Worship Leader",
    img: "https://i.pravatar.cc/150?u=5",
  },
];

export const INITIAL_SETLISTS: Setlist[] = [
  {
    id: 1,
    name: "Easter Sunday Service",
    date: "2026-04-05",
    leader: "Michael Brown",
    songs: [SONGS[0], SONGS[1], SONGS[5]],
  },
  {
    id: 2,
    name: "Youth Night - April",
    date: "2026-04-12",
    leader: "Jane Smith",
    songs: [SONGS[9], SONGS[10], SONGS[21]],
  },
  {
    id: 3,
    name: "Worship Night",
    date: "2026-04-19",
    leader: "David Evans",
    songs: [SONGS[12], SONGS[13], SONGS[14], SONGS[16]],
  },
  {
    id: 4,
    name: "Sunday Morning Service",
    date: "2026-04-26",
    leader: "Sarah Jenkins",
    songs: [SONGS[4], SONGS[6], SONGS[8]],
  },
  {
    id: 5,
    name: "Revival Night",
    date: "2026-05-03",
    leader: "John Doe",
    songs: [SONGS[15], SONGS[17], SONGS[18], SONGS[19]],
  },
  {
    id: 6,
    name: "Children's Sunday",
    date: "2026-05-10",
    leader: "Jane Smith",
    songs: [SONGS[0], SONGS[7]],
  },
  {
    id: 7,
    name: "Midweek Prayer",
    date: "2026-05-14",
    leader: "David Evans",
    songs: [SONGS[2], SONGS[3], SONGS[5]],
  },
  {
    id: 8,
    name: "Community Outreach",
    date: "2026-05-17",
    leader: "Michael Brown",
    songs: [SONGS[11], SONGS[20], SONGS[1]],
  },
  {
    id: 9,
    name: "Healing Service",
    date: "2026-05-24",
    leader: "Sarah Jenkins",
    songs: [SONGS[3], SONGS[4], SONGS[18]],
  },
  {
    id: 10,
    name: "Night of Praise",
    date: "2026-05-31",
    leader: "John Doe",
    songs: [SONGS[21], SONGS[10], SONGS[12], SONGS[14]],
  },
];
